export const Commands = {
    CLEAN_WHITESPACE: 'pancho.cleanWhitespace',
    CLEAN_LINE_ENDINGS: 'pancho.cleanLineEndings',
    CONVERT_TABS_TO_SPACES: 'pancho.convertTabsToSpaces',
    CONVERT_SPACES_TO_TABS: 'pancho.convertSpacesToTabs',
    TO_UPPER_CASE: 'pancho.toUpperCase',
    TO_LOWER_CASE: 'pancho.toLowerCase',
    TO_TITLE_CASE: 'pancho.toTitleCase',
    TRIM_LINES: 'pancho.trimLines',
    LINE_ENDINGS_TO_SPACES: 'pancho.lineEndingsToSpaces',
    INCREASE_INDENT: 'pancho.increaseIndent',
    DECREASE_INDENT: 'pancho.decreaseIndent',
    INSERT_SHORT_TIME: 'pancho.insertShortTime',
    INSERT_LONG_TIME: 'pancho.insertLongTime',
    INSERT_DATE_TIME: 'pancho.insertDateTime',
    COMMENT_LINE: 'pancho.commentLine',
    UNCOMMENT_LINE: 'pancho.uncommentLine',
    COMMENT_BLOCK: 'pancho.commentBlock',
    UNCOMMENT_BLOCK: 'pancho.uncommentBlock',
    REMOVE_DUPLICATE_LINES: 'pancho.removeDuplicateLines',
    SORT_ASCENDING: 'pancho.sortAscending',
    SORT_DESCENDING: 'pancho.sortDescending',
    REVERSE_LINES: 'pancho.reverseLines',
    JOIN_LINES: 'pancho.joinLines',
    REMOVE_EMPTY_LINES: 'pancho.removeEmptyLines',
    TO_WINDOWS_EOL: 'pancho.toWindowsEOL',
    TO_UNIX_EOL: 'pancho.toUnixEOL',
    TO_MAC_EOL: 'pancho.toMacEOL',
    PASTE_WITHOUT_LINE_BREAK: 'pancho.pasteWithoutLineBreak',
    COPY_TO_MULTIPLE_LINES: 'pancho.copyToMultipleLines',
    FORMAT_AS_CSV: 'pancho.formatAsCSV',
    INSERT_DEGREE: 'pancho.insertDegree',
    INSERT_COPYRIGHT: 'pancho.insertCopyright',
    INSERT_REGISTERED: 'pancho.insertRegistered',
    INSERT_TRADEMARK: 'pancho.insertTrademark',
    INSERT_SECTION: 'pancho.insertSection',
    INSERT_PILCROW: 'pancho.insertPilcrow',
    INSERT_ELLIPSIS: 'pancho.insertEllipsis',
    INSERT_BULLET: 'pancho.insertBullet',
    INSERT_EURO: 'pancho.insertEuro',
    INSERT_POUND: 'pancho.insertPound',
    INSERT_YEN: 'pancho.insertYen',
    COUNT_WORDS: 'pancho.countWords',
    COUNT_CHARACTERS: 'pancho.countCharacters',
    COUNT_LINES: 'pancho.countLines',
    REMOVE_DUPLICATE_WORDS: 'pancho.removeDuplicateWords',
    NUMBER_LINES: 'pancho.numberLines',
    REMOVE_LINE_NUMBERS: 'pancho.removeLineNumbers',
    SLUGIFY: 'pancho.slugify',
    REVERSE_WORDS: 'pancho.reverseWords',
    RANDOMIZE_LINES: 'pancho.randomizeLines',
    MINIFY_JSON: 'pancho.minifyJSON',
    PRETTIFY_JSON: 'pancho.prettifyJSON',
    MINIFY_HTML: 'pancho.minifyHTML',
    PRETTIFY_HTML: 'pancho.prettifyHTML',
    MINIFY_CSS: 'pancho.minifyCSS',
    PRETTIFY_CSS: 'pancho.prettifyCSS',
    MINIFY_JS: 'pancho.minifyJS',
    PRETTIFY_JS: 'pancho.prettifyJS',
    HTML_ENTITIES_ENCODE: 'pancho.htmlEntitiesEncode',
    HTML_ENTITIES_DECODE: 'pancho.htmlEntitiesDecode',
    BASE64_ENCODE: 'pancho.base64Encode',
    BASE64_DECODE: 'pancho.base64Decode',
    URL_ENCODE: 'pancho.urlEncode',
    URL_DECODE: 'pancho.urlDecode',
    HEX_TO_RGB: 'pancho.hexToRgb',
    RGB_TO_HEX: 'pancho.rgbToHex',
    LOREM_IPSUM: 'pancho.loremIpsum',
    FORMAT_SQL: 'pancho.formatSQL',
    PRETTIFY_XML: 'pancho.prettifyXML',
    MINIFY_XML: 'pancho.minifyXML',
    GENERATE_UUID: 'pancho.generateUUID',
    GENERATE_RANDOM_STRING: 'pancho.generateRandomString',
    HASH_MD5: 'pancho.hashMD5',
    HASH_SHA256: 'pancho.hashSHA256',
    TO_BINARY: 'pancho.toBinary',
    FROM_BINARY: 'pancho.fromBinary',
    TO_HEX: 'pancho.toHex',
    FROM_HEX: 'pancho.fromHex',
} as const;

export type CommandName = typeof Commands[keyof typeof Commands];

export interface Command {
    name: CommandName;
    title: string;
}

export const CommandList: Command[] = [
    { name: Commands.CLEAN_WHITESPACE, title: 'Limpiar espacios en blanco' },
    { name: Commands.CLEAN_LINE_ENDINGS, title: 'Limpiar saltos de línea' },
    { name: Commands.CONVERT_TABS_TO_SPACES, title: 'Convertir tabs a espacios' },
    { name: Commands.CONVERT_SPACES_TO_TABS, title: 'Convertir espacios a tabs' },
    { name: Commands.TO_UPPER_CASE, title: 'Convertir a MAYÚSCULAS' },
    { name: Commands.TO_LOWER_CASE, title: 'Convertir a minúsculas' },
    { name: Commands.TO_TITLE_CASE, title: 'Convertir a Título' },
    { name: Commands.TRIM_LINES, title: 'Recortar líneas' },
    { name: Commands.LINE_ENDINGS_TO_SPACES, title: 'Convertir saltos de línea a espacios' },
    { name: Commands.INCREASE_INDENT, title: 'Aumentar indentación' },
    { name: Commands.DECREASE_INDENT, title: 'Disminuir indentación' },
    { name: Commands.INSERT_SHORT_TIME, title: 'Fecha y hora corta' },
    { name: Commands.INSERT_LONG_TIME, title: 'Fecha y hora larga' },
    { name: Commands.INSERT_DATE_TIME, title: 'Fecha y hora (dd-MM-yyyy hh:mm:ss)' },
    { name: Commands.COMMENT_LINE, title: 'Comentar línea' },
    { name: Commands.UNCOMMENT_LINE, title: 'Descomentar línea' },
    { name: Commands.COMMENT_BLOCK, title: 'Comentar bloque' },
    { name: Commands.UNCOMMENT_BLOCK, title: 'Descomentar bloque' },
    { name: Commands.REMOVE_DUPLICATE_LINES, title: 'Eliminar líneas duplicadas' },
    { name: Commands.SORT_ASCENDING, title: 'Ordenar A-Z' },
    { name: Commands.SORT_DESCENDING, title: 'Ordenar Z-A' },
    { name: Commands.REVERSE_LINES, title: 'Revertir líneas' },
    { name: Commands.JOIN_LINES, title: 'Unir líneas' },
    { name: Commands.REMOVE_EMPTY_LINES, title: 'Eliminar líneas vacías' },
    { name: Commands.TO_WINDOWS_EOL, title: 'Convertir a Windows (CRLF)' },
    { name: Commands.TO_UNIX_EOL, title: 'Convertir a Unix (LF)' },
    { name: Commands.TO_MAC_EOL, title: 'Convertir a Mac (CR)' },
    { name: Commands.PASTE_WITHOUT_LINE_BREAK, title: 'Pegar sin salto de línea' },
    { name: Commands.COPY_TO_MULTIPLE_LINES, title: 'Copiar a múltiples líneas' },
    { name: Commands.FORMAT_AS_CSV, title: 'Formatear como CSV' },
    { name: Commands.INSERT_DEGREE, title: 'Grado (°)' },
    { name: Commands.INSERT_COPYRIGHT, title: 'Copyright (©)' },
    { name: Commands.INSERT_REGISTERED, title: 'Registrado (®)' },
    { name: Commands.INSERT_TRADEMARK, title: 'Trademark (™)' },
    { name: Commands.INSERT_SECTION, title: 'Sección (§)' },
    { name: Commands.INSERT_PILCROW, title: 'Pilcrow (¶)' },
    { name: Commands.INSERT_ELLIPSIS, title: 'Puntos suspensivos (…)' },
    { name: Commands.INSERT_BULLET, title: 'Viñeta (•)' },
    { name: Commands.INSERT_EURO, title: 'Euro (€)' },
    { name: Commands.INSERT_POUND, title: 'Libra (£)' },
    { name: Commands.INSERT_YEN, title: 'Yen (¥)' },
    { name: Commands.COUNT_WORDS, title: 'Contar palabras' },
    { name: Commands.COUNT_CHARACTERS, title: 'Contar caracteres' },
    { name: Commands.COUNT_LINES, title: 'Contar líneas' },
    { name: Commands.REMOVE_DUPLICATE_WORDS, title: 'Eliminar palabras duplicadas' },
    { name: Commands.NUMBER_LINES, title: 'Numerar líneas' },
    { name: Commands.REMOVE_LINE_NUMBERS, title: 'Quitar números de línea' },
    { name: Commands.SLUGIFY, title: 'Generar slug URL' },
    { name: Commands.REVERSE_WORDS, title: 'Revertir palabras' },
    { name: Commands.RANDOMIZE_LINES, title: 'Aleatorizar líneas' },
    { name: Commands.MINIFY_JSON, title: 'Minificar JSON' },
    { name: Commands.PRETTIFY_JSON, title: 'Formatear JSON' },
    { name: Commands.MINIFY_HTML, title: 'Minificar HTML' },
    { name: Commands.PRETTIFY_HTML, title: 'Formatear HTML' },
    { name: Commands.MINIFY_CSS, title: 'Minificar CSS' },
    { name: Commands.PRETTIFY_CSS, title: 'Formatear CSS' },
    { name: Commands.MINIFY_JS, title: 'Minificar JavaScript' },
    { name: Commands.PRETTIFY_JS, title: 'Formatear JavaScript' },
    { name: Commands.HTML_ENTITIES_ENCODE, title: 'Codificar HTML entities' },
    { name: Commands.HTML_ENTITIES_DECODE, title: 'Decodificar HTML entities' },
    { name: Commands.BASE64_ENCODE, title: 'Codificar Base64' },
    { name: Commands.BASE64_DECODE, title: 'Decodificar Base64' },
    { name: Commands.URL_ENCODE, title: 'Codificar URL' },
    { name: Commands.URL_DECODE, title: 'Decodificar URL' },
    { name: Commands.HEX_TO_RGB, title: 'Hex a RGB' },
    { name: Commands.RGB_TO_HEX, title: 'RGB a Hex' },
    { name: Commands.LOREM_IPSUM, title: 'Generar Lorem Ipsum' },
    { name: Commands.FORMAT_SQL, title: 'Formatear SQL' },
    { name: Commands.PRETTIFY_XML, title: 'Formatear XML' },
    { name: Commands.MINIFY_XML, title: 'Minificar XML' },
    { name: Commands.GENERATE_UUID, title: 'Generar UUID' },
    { name: Commands.GENERATE_RANDOM_STRING, title: 'Generar cadena aleatoria' },
    { name: Commands.HASH_MD5, title: 'Hash MD5' },
    { name: Commands.HASH_SHA256, title: 'Hash SHA-256' },
    { name: Commands.TO_BINARY, title: 'Texto a binario' },
    { name: Commands.FROM_BINARY, title: 'Binario a texto' },
    { name: Commands.TO_HEX, title: 'Texto a hexadecimal' },
    { name: Commands.FROM_HEX, title: 'Hexadecimal a texto' },
];