export const Commands = {
    CLEAN_WHITESPACE: 'pancho.cleanWhitespace',
    CLEAN_LINE_ENDINGS: 'pancho.cleanLineEndings',
    CONVERT_TABS_TO_SPACES: 'pancho.convertTabsToSpaces',
    CONVERT_SPACES_TO_TABS: 'pancho.convertSpacesToTabs',
    TO_UPPER_CASE: 'pancho.toUpperCase',
    TO_LOWER_CASE: 'pancho.toLowerCase',
    TO_TITLE_CASE: 'pancho.toTitleCase',
    TRIM_LINES: 'pancho.trimLines',
    LINE_ENDINGS_TO_SPACES: 'pancho.lineEndingsToSpaces',
    INCREASE_INDENT: 'pancho.increaseIndent',
    DECREASE_INDENT: 'pancho.decreaseIndent',
    INSERT_SHORT_TIME: 'pancho.insertShortTime',
    INSERT_LONG_TIME: 'pancho.insertLongTime',
    INSERT_DATE_TIME: 'pancho.insertDateTime',
    COMMENT_LINE: 'pancho.commentLine',
    UNCOMMENT_LINE: 'pancho.uncommentLine',
    COMMENT_BLOCK: 'pancho.commentBlock',
    UNCOMMENT_BLOCK: 'pancho.uncommentBlock',
    REMOVE_DUPLICATE_LINES: 'pancho.removeDuplicateLines',
    SORT_ASCENDING: 'pancho.sortAscending',
    SORT_DESCENDING: 'pancho.sortDescending',
    REVERSE_LINES: 'pancho.reverseLines',
    JOIN_LINES: 'pancho.joinLines',
    REMOVE_EMPTY_LINES: 'pancho.removeEmptyLines',
    TO_WINDOWS_EOL: 'pancho.toWindowsEOL',
    TO_UNIX_EOL: 'pancho.toUnixEOL',
    TO_MAC_EOL: 'pancho.toMacEOL',
} as const;

export type CommandName = typeof Commands[keyof typeof Commands];

export interface Command {
    name: CommandName;
    title: string;
}

export const CommandList: Command[] = [
    { name: Commands.CLEAN_WHITESPACE, title: 'Limpiar espacios en blanco' },
    { name: Commands.CLEAN_LINE_ENDINGS, title: 'Limpiar saltos de línea' },
    { name: Commands.CONVERT_TABS_TO_SPACES, title: 'Convertir tabs a espacios' },
    { name: Commands.CONVERT_SPACES_TO_TABS, title: 'Convertir espacios a tabs' },
    { name: Commands.TO_UPPER_CASE, title: 'Convertir a MAYÚSCULAS' },
    { name: Commands.TO_LOWER_CASE, title: 'Convertir a minúsculas' },
    { name: Commands.TO_TITLE_CASE, title: 'Convertir a Título' },
    { name: Commands.TRIM_LINES, title: 'Recortar líneas' },
    { name: Commands.LINE_ENDINGS_TO_SPACES, title: 'Convertir saltos de línea a espacios' },
    { name: Commands.INCREASE_INDENT, title: 'Aumentar indentación' },
    { name: Commands.DECREASE_INDENT, title: 'Disminuir indentación' },
    { name: Commands.INSERT_SHORT_TIME, title: 'Fecha y hora corta' },
    { name: Commands.INSERT_LONG_TIME, title: 'Fecha y hora larga' },
    { name: Commands.INSERT_DATE_TIME, title: 'Fecha y hora (dd-MM-yyyy hh:mm:ss)' },
    { name: Commands.COMMENT_LINE, title: 'Comentar línea' },
    { name: Commands.UNCOMMENT_LINE, title: 'Descomentar línea' },
    { name: Commands.COMMENT_BLOCK, title: 'Comentar bloque' },
    { name: Commands.UNCOMMENT_BLOCK, title: 'Descomentar bloque' },
    { name: Commands.REMOVE_DUPLICATE_LINES, title: 'Eliminar líneas duplicadas' },
    { name: Commands.SORT_ASCENDING, title: 'Ordenar A-Z' },
    { name: Commands.SORT_DESCENDING, title: 'Ordenar Z-A' },
    { name: Commands.REVERSE_LINES, title: 'Revertir líneas' },
    { name: Commands.JOIN_LINES, title: 'Unir líneas' },
    { name: Commands.REMOVE_EMPTY_LINES, title: 'Eliminar líneas vacías' },
    { name: Commands.TO_WINDOWS_EOL, title: 'Convertir a Windows (CRLF)' },
    { name: Commands.TO_UNIX_EOL, title: 'Convertir a Unix (LF)' },
    { name: Commands.TO_MAC_EOL, title: 'Convertir a Mac (CR)' },
];